### PR TITLE
spine.janelia.org -> services.itanna.io

### PR DESCRIPTION
**Pull request by perlman**
Update of hostname used for services hosted on spine.

~~TODO: Update hostname for static file serving (brain meshes).~~

Should be good to go.

### CODE REVIEW

**Comment by emilkind** [comment]
I get

`Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [spine.janelia.org] Connection timeout after 10002 ms` 

when I call `flywire_xyz2id()` and I wonder if this pull request would fix the error or if there is another cause for this error?

**Comment by perlman** [comment]
The server is currently being moved (which was the reason for the PR.)

We expect it to be online by early afternoon (eastern US time).

**Comment by emilkind** [comment]
Great, thank you!

**Comment by jefferis** [comment]
@emilkind you can do 
```
flywire_xyz2id(pts, method='cloudvolume')
```
in the interim. But it's much slower.

**Comment by emilkind** [comment]
Thank you, Greg.

**Comment by emilkind** [comment]
Thank You very much.

Best,
Emil

**Pull request merged**
